# Generated by Django 4.1 on 2022-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('GESTAO', 'Gestão '), ('EDUCACAO_PERMANENTE_E_CONTINUADA', 'Educação Permanente e Continuada'), ('PESQUISA_EM_ENFERMAGEM_E_SAUDE', 'Pesquisa em enfermagem e saúde'), ('DEV_DE_PROJETO_E_PESQUISA', 'Desenvolvimento de projetos e pesquisas')], max_length=150),
        ),
    ]
